Eq2 123 evaluer le milieu de stage
PraiseTSun/ProjetStage02 pull request #12
Opened 2022-11-09 16:53 UTC by yanzhou87

2022-11-11 20:31 UTC, McLovin3 requested changes
![image](https://user-images.githubusercontent.com/89847869/201426172-83e89f2d-7136-4f93-b629-0aded364e4fc.png)
On peut cliquer sur enregistrer même quand le formulaire est vide (Reset la page)

![image](https://user-images.githubusercontent.com/89847869/201426248-edf150b3-4014-472c-aea8-d684a0da71b6.png)
Cliquer le bouton signer reset la page (Devrait reafficher le forumulaire directement)

À part ça très belle page, le UI est très beau :D

2022-11-11 20:31 UTC, McLovin3 commented on frontend/src/services/gestionnaireServices/GestionnaireFetchService.tsx
> +export const putContrats = (token: string): Promise<Response> => {
Peut-être spécifier que c'est un get (putGetContrats)

2022-11-11 20:31 UTC, McLovin3 commented on frontend/src/pages/gestionnairePages/EvaluerLeMilieuDeStage.tsx
> +    const [contratId, setContratId] = useState<number>(0)
À la place de tout ces states, tu pourrait avoir un objet qui contient tout ces champs et donc tu pourrait seulement avoir un useState pour cet objet, mais ces seulement si tu veut (Ou a le temps)

2022-11-11 20:31 UTC, McLovin3 commented on frontend/src/pages/gestionnairePages/EvaluerLeMilieuDeStage.tsx
> +    const [contratId, setContratId] = useState<number>(0)
Enfaite comme tu a fait plus haut

2022-11-11 20:31 UTC, McLovin3 commented on frontend/src/pages/gestionnairePages/EvaluerLeMilieuDeStage.tsx
> +    const notShowFormulaires = () => {
notShowFormulaires pourrait etre hideFormulaires

2022-11-11 20:31 UTC, McLovin3 commented on frontend/src/pages/gestionnairePages/EvaluerLeMilieuDeStage.tsx
> +                                                <option value="totalementEnAccord">Totalement en accord
Pour tout les champs avec Totalement en accord, plutot en accord, etc. Tu pourrait faire un component, ce qui réduirait la taille, mais encore c'est seulement si tu veut (Ou a le temps)

2022-11-14 15:42 UTC, yanzhou87 commented on frontend/src/pages/gestionnairePages/EvaluerLeMilieuDeStage.tsx
> +    const [contratId, setContratId] = useState<number>(0)
j'ai essayé de faire ça, mais le code est plus long que avant, donc j'ai laissé le code comme j'avais écrit

2022-11-14 16:08 UTC, McLovin3 commented
![image](https://user-images.githubusercontent.com/89847869/201708487-85ef63ca-c243-4ff7-8885-a59f1e583683.png)

Oublier la validation d'un champs et mettre un min et max pour les nombres

Bon travail!

2022-11-14 22:20 UTC, McLovin3 requested changes

2022-11-14 22:20 UTC, McLovin3 commented on frontend/src/pages/gestionnairePages/EvaluerLeMilieuDeStage.tsx
> +            setWaiting(false)
Je sais pas si cela et tout les lignes en bas serve à quelque chose si tu ferme le component

2022-11-14 22:20 UTC, McLovin3 commented on frontend/src/pages/gestionnairePages/EvaluerLeMilieuDeStage.tsx
> +                                                <Form.Control type="number" minLength={1} required min={0}
Le alert qui dit de remplir tout les champs apparait quand même si la valeur est 0 (Meme choses avec les 2 autres nombres)

2022-11-15 15:27 UTC, yanzhou87 commented on frontend/src/pages/gestionnairePages/EvaluerLeMilieuDeStage.tsx
> +            }
si il a pas retourné ok, il va aller dans generateAlert()

2022-11-16 23:02 UTC, closed without merging