Eq2 84 status de validation de mon cv
PraiseTSun/ProjetStage02 pull request #2
Opened 2022-11-01 18:02 UTC by yanzhou87

2022-11-01 21:48 UTC, McLovin3 commented on frontend/src/pages/studentPages/StudentCvUploadPage.tsx
> +export const statusCV : CvStatus = {
Ça sert à quoi?

2022-11-01 21:48 UTC, McLovin3 commented on frontend/src/pages/studentPages/StudentCvUploadPage.tsx
> +        // const enc = new TextEncoder(); // always utf-8
Code mort

2022-11-04 16:09 UTC, McLovin3 requested changes
![image](https://user-images.githubusercontent.com/89847869/200022448-31f9a270-4262-47bb-97e5-f53af7d0a5c9.png)
Une couple de warning React 

![image](https://user-images.githubusercontent.com/89847869/200022657-7a089004-fc06-4cd5-a8fe-33b82a9bbec1.png)
Bouton cv sur la page de student Cv Validation

![image](https://user-images.githubusercontent.com/89847869/200022946-2da26f7f-e817-4ad0-aac9-2d28e8f053d4.png)
Même chose avec bouton cv à valider lorsque aucun cv à validé

(Pour les deux disable les boutons lorsque cv/cvToValidate="")

C'est bon à part, beau travail

2022-11-05 00:37 UTC, yanzhou87 commented on frontend/src/pages/studentPages/StudentCvUploadPage.tsx
> +        const fetcheStatusCV = async () => {
corrige

2022-11-07 21:18 UTC, McLovin3 commented on frontend/src/pages/studentPages/StudentCvUploadPage.tsx
> +                        <th data-testid="RefusalMessage"> Refusal Message :</th>
Mettre en français

2022-11-07 21:22 UTC, McLovin3 commented on frontend/src/pages/studentPages/StudentCvUploadPage.tsx
> +                                    <Button className="btn" disabled onClick={async () => await getCvToValidate()}>Cv To
Et peut appeler setShowCvToValidate(true) directement

2022-11-07 21:22 UTC, McLovin3 commented on frontend/src/pages/studentPages/StudentCvUploadPage.tsx
> +                                    <Button className="btn" disabled onClick={async () => await getCv()}>CV</Button>
Et peut appeler setShowCvToValidate(true) directement

2022-11-07 21:27 UTC, McLovin3 commented on frontend/src/pages/studentPages/StudentCvUploadPage.tsx
>          event.preventDefault();
if (response.ok) ajouter la une ligne pour mettre user.cvToValidate au cv que tu a upload

2022-11-07 21:27 UTC, McLovin3 commented on frontend/src/pages/studentPages/StudentCvUploadPage.tsx
> +                        <th>Cv To Validate :</th>
En français

2022-11-07 21:29 UTC, McLovin3 commented on frontend/src/pages/studentPages/StudentCvUploadPage.tsx
>      const [cv, setCv] = useState<number[]>([0])
Changer nom à cvToValidate et setCvToValidate

2022-11-07 23:04 UTC, McLovin3 requested changes
![image](https://user-images.githubusercontent.com/89847869/200434013-e5bc6082-97cf-4635-838c-0091c463748e.png)
Adresser les warnings

2022-11-07 23:04 UTC, McLovin3 commented on frontend/src/pages/studentPages/StudentCvUploadPage.tsx
> +                    connectedUser.cvToValidate =  JSON.stringify(cvToValidate)
Marche pas (cvToValidate semble être remit à "" lorsque la page change)

2022-11-08 19:24 UTC, merged