Eq2 168 user notification backend
PraiseTSun/ProjetStage02 pull request #27
Opened 2022-11-24 15:27 UTC by PraiseTSun

2022-11-25 03:42 UTC, MassinissaDjellouli requested changes
Fait attentions au pluriels, sinon good job

2022-11-25 03:42 UTC, MassinissaDjellouli commented on src/main/java/projet/projetstage02/dto/applications/ApplicationListDTO.java
> +    public boolean hasApply(long id){
Renommer en hasApplied

2022-11-25 03:42 UTC, MassinissaDjellouli commented on src/main/java/projet/projetstage02/service/CompanyService.java
> +            nb += (int) count;
pourquoi int au lieu de long?

2022-11-25 03:42 UTC, MassinissaDjellouli commented on src/main/java/projet/projetstage02/service/GestionnaireService.java
> +    private int getUnvalidatedUserNumber() {
renommer en getAmountOfUnvalidatedUsers. le "Number" a la fin n'est pas clair

2022-11-25 03:42 UTC, MassinissaDjellouli commented on src/main/java/projet/projetstage02/service/GestionnaireService.java
> +    private int getCvToValidateNumber() {
renommer en getAmountOf au lieu de Number.

2022-11-25 03:42 UTC, MassinissaDjellouli commented on src/main/java/projet/projetstage02/service/GestionnaireService.java
> +    private int getOfferToValidateNumber() {
renommer en getAmountOf au lieu de Number.

2022-11-25 03:42 UTC, MassinissaDjellouli commented on src/main/java/projet/projetstage02/service/GestionnaireService.java
> +    private int getContractInNeedToBeCreate() {
created pas create

2022-11-25 03:42 UTC, MassinissaDjellouli commented on src/test/java/projet/projetstage02/service/GestionnaireServiceTest.java
> +
peut-etre séparer celui la en plusieurs tests vu la longueur

2022-11-26 05:44 UTC, PraiseTSun commented on src/test/java/projet/projetstage02/service/GestionnaireServiceTest.java
> +
Non c'est le Happy Day test

2022-11-26 19:09 UTC, MassinissaDjellouli approved these changes

2022-11-27 05:14 UTC, merged